version: '3'
services:
  meta:
    name: meta
    build:
      context: .
      target: production
      dockerfile: Dockerfile-prod
    ports:
      - 25575:25565  # Meta
    restart: always
    stdin_open: true  # -i
    tty: true  # -t
    logging:
      driver: json-file
      options:
        max-size: "500k"
        max-file: "10"
    volumes:
      - type: volume
        source: worlds
        target: /mnt/worlds
        volume:
          nocopy: true
      - type: volume
        source: plugins
        target: /opt/paper/plugins
        volume:
          nocopy: true
      - type: volume
        source: logs
        target: /opt/paper/logs
        volume:
          nocopy: true
      # - type: volume#TODO: 共享banlist，submodule实现
      #   source: ban/banned-ips.json
      #   target: /opt/paper/banned-ips.json
      #   volume:
      #     nocopy: true
      # - type: volume
      #   source: ban/banned-players.json
      #   target: /opt/paper/banned-players.json
      #   volume:
      #     nocopy: true

volumes:
  worlds:
    driver_opts:
      type: "nfs"
      o: "addr=nfs.inner.s-2.link,nolock,soft,rw"
      device: ":/rrpu8kxb/meta/worlds"
  plugins:
    driver_opts:
      type: "nfs"
      o: "addr=nfs.inner.s-2.link,nolock,soft,rw"
      device: ":/rrpu8kxb/meta/plugins"
  logs:
    driver_opts:
      type: "nfs"
      o: "addr=nfs.inner.s-2.link,nolock,soft,rw"
      device: ":/rrpu8kxb/meta/logs"
  
  ban:
    driver_opts:
      type: "nfs"
      o: "addr=nfs.inner.s-2.link,nolock,soft,rw"
      device: ":/rrpu8kxb/meta/banlist"
