# This file will build a CORE image, and this file will be only used by CI

#=================================================
# 1. fetch paper jar file
#=================================================

FROM python:3 AS fetch
ARG PROJECT='paper'
ARG VERSION='1.18.2'
RUN mkdir /opt/fetch-paper-api
COPY ./fetch-paper-api/main.py ./fetch-paper-api/requirements.txt  /opt/fetch-paper-api/
WORKDIR /opt/fetch-paper-api
RUN pip install --no-cache-dir -r requirements.txt
RUN python main.py $PROJECT $VERSION

#=================================================
# 2. First run and download cache folder
#=================================================

FROM openjdk:17 AS pre-cache

# System prepare
ENV TZ=Asia/Shanghai JAVA_MEMORY=256M

RUN mkdir /opt/paper
WORKDIR /opt/paper

# TODO: Use paperclip, not paper to do perepare
COPY --from=fetch /opt/fetch-paper-api/target.jar ./paper.jar
COPY ./run.sh /opt/paper/run.sh

# First run to cache
COPY ./run.sh .
RUN sh run.sh

#=================================================
# 3. COPY game folder into a game-ready image
#=================================================

FROM alpine:latest AS game-core

ENV TZ=Asia/Shanghai JAVA_MEMORY=256M

RUN mkdir /opt/paper
WORKDIR /opt/paper

COPY --from=pre-cache /opt/paper /opt/paper

#=================================================
# 4. Test stage
#=================================================

FROM amazoncorretto:17 AS test

# System Environment
ENV TZ=Asia/Shanghai JAVA_MEMORY=4G LANG=en_US.utf8
RUN mkdir /opt/paper
WORKDIR /opt/paper

# Copy files
COPY --from=game-core /opt/paper .

# Config
RUN sed -i "s/eula=false/eula=true/g" eula.txt
COPY ./config/server.properties\ 
     ./config/bukkit.yml\ 
     ./config/spigot.yml\ 
     ./config/paper.yml\ 
     ./

# Avatar
COPY ./design/server-icon.png .

ENTRYPOINT ["sh", "/opt/paper/run.sh"]
