settings:
  allow-end: true
  warn-on-overload: false  # default is true
  permissions-file: permissions.yml
  update-folder: update
  plugin-profiling: false
  connection-throttle: -1  # default is 4000
  query-plugins: true
  deprecated-verbose: default
  shutdown-message: "[FATAL]::meta-core::Core is down."
  minimum-api: none
  world-container:  /mnt/worlds # point to worlds folder
spawn-limits:
  monsters: 40
  animals: 15
  water-animals: 5
  water-ambient: 20
  water-underground-creature: 5
  ambient: 10
chunk-gc:
  period-in-ticks: 1200
ticks-per:
  animal-spawns: 400
  monster-spawns: 1
  water-spawns: 1
  water-ambient-spawns: 1
  water-underground-creature-spawns: 1
  ambient-spawns: 1
  autosave: 1200  # Every minute process a save  # default is 0
aliases: now-in-commands.yml
