version: '1.0'
name: pipeline-20220112
displayName: alpha
triggers:
  push:
    branches:
      prefix:
        - master
stages:
  - name: stage-a7d40da6
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        repository: https://hub.docker.com/repository/docker/1ris/oar-cache
        username: 1ris
        password: ee89465c-bca5-4059-aebc-4b1d467d8216
        tag: meta-core-alpha-${GITEE_PIPELINE_BUILD_NUMBER}
        dockerfile: ./Dockerfile-cache
        isCache: false
  - name: stage-176a462a
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactRepository: default
        artifactName: output
permissions:
  - role: admin
    members: []
